### ISSUE TITLE
Gene name to the left of the line?

### ISSUE THREAD

**Issue by nroak** [deeptools/pyGenomeTracks#176] opened 2020-01-24 21:20 UTC
I realized that all the gene names are always to the right side of the line. However, if I just want to zoom in to the promoter region of a gene, I don't see a gene name at all since the end of that line is not in the view.
Is there a way to toggle the position of the gene name to either the left of the line or below the line as we see in the UCSC genome browser or IGV?

[wbp1l.pdf](https://github.com/deeptools/pyGenomeTracks/files/4110765/wbp1l.pdf)
<img width="1025" alt="Screen Shot 2020-01-24 at 3 20 12 PM" src="https://user-images.githubusercontent.com/24547900/73104856-0b724280-3ebd-11ea-8237-71e72f12b436.png">

**Comment by lldelisle** [comment] 2020-01-27 10:24
Hi,
Thanks for using pyGenomeTracks. You are right, this is indeed something we should improve. I just wrote a PR where the genes will be written on the right in the margin when the option: `labels_in_margin = true` when it goes over the region plotted:
Without the option:
https://github.com/lldelisle/pyGenomeTracks/raw/labels_in_margin/pygenometracks/tests/test_data/master_bed_and_gtf_zoom.png
With the option:
https://github.com/lldelisle/pyGenomeTracks/raw/labels_in_margin/pygenometracks/tests/test_data/master_bed_and_gtf_zoom_lim_ral.png
Would it solve your issue?

**Comment by nroak** [comment] 2020-01-27 15:08
I think this will be a good quick fix, but it would be really nice to have the label before the beginning of the line since users are more used to the UCSC format. Thank you very much for adding this fix so quickly.
Also thanks a ton for this tool and amazing documentation. It was very easy to use and produces beautiful figures.

**Comment by lldelisle** [comment] 2020-01-27 15:11
I understand your point, the issue is that when we have a colorbar on the left, I am afraid it will collapse but this may be doable if we put the colorbar really left. I will try to add the option `labels_position = left`.

**Comment by nroak** [comment] 2020-01-27 15:20
I see, is it possible to keep the gene names within the track area like other gene names and then toggle left vs right of the line depending on the space available on either side? That way it won't interfere with the axes.

**Comment by lldelisle** [comment] 2020-01-27 15:29
Yes I can try.

**Comment by lldelisle** [comment] 2020-01-27 15:52
![master_bed_all_label_inside](https://user-images.githubusercontent.com/30404086/73189826-52627100-4125-11ea-88d4-bffd3da224ae.png)
Like this?

**Comment by nroak** [comment] 2020-01-27 16:08
This is perfect! Thank you so much for the quick fix.

**Comment by lldelisle** [comment] 2020-01-27 16:12
For the moment, it is not merged to the main branch. I will keep you updated.

**Comment by lldelisle** [comment] 2020-03-24 10:20
I is now included in version 3.3.

**Closed by lldelisle** 2020-03-24 10:20 UTC
