### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by iamjli** [deeptools/pyGenomeTracks#61] opened 2019-01-24 17:58 UTC
https://github.com/deeptools/pyGenomeTracks/blob/2b434211b484c25fa7d21dd3dd821c67a4da30d3/pygenometracks/tracks/HiCMatrixTrack.py#L54

I believe this should be 

```
if "region" in self.properties: 
```

**Comment by fidelram** [comment] 2019-01-28 08:32
did you get an error? I think that self.properties['region'] is initialized
previously.

**Comment by LeilyR** [comment] 2019-02-19 08:42
properties['region'] is set after reading --region from the command line

**Comment by lldelisle** [comment] 2019-12-17 15:58
Hi,
I am sorry but we could not reproduce the error. 
I will close the issue. 
Feel free to reopen it if you still need help.

**Closed by lldelisle** 2019-12-17 15:58 UTC
